#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# Depends on sensio/framework-extra-bundle:^3.0 and doctrine/annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
